# Generated by Django 5.2.1 on 2025-06-02 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RewardWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_username', models.CharField(max_length=100, unique=True)),
                ('wallet_fullname', models.CharField(max_length=100)),
                ('wallet_communication_email', models.EmailField(max_length=254)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RewardOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_id', models.CharField(max_length=50)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('payment_status', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=100)),
                ('reward_rate', models.FloatField(default=0.0)),
                ('order_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reward.rewardwallet', to_field='wallet_username')),
            ],
        ),
    ]
