# Generated by Django 5.2.1 on 2025-06-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardorders',
            name='status',
        ),
        migrations.AddField(
            model_name='rewardorders',
            name='valid_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rewardorders',
            name='valid_to',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rewardorders',
            name='wallet_status',
            field=models.BooleanField(default=False),
        ),
    ]
