# Generated by Django 5.2.1 on 2025-06-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0002_remove_rewardorders_status_rewardorders_valid_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rewardorders',
            old_name='wallet_status',
            new_name='reward_status',
        ),
    ]
