# Generated by Django 5.2.1 on 2025-06-02 11:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0003_rename_wallet_status_rewardorders_reward_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_id', models.CharField(max_length=50)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(max_length=100)),
                ('reward_rate', models.FloatField(default=0.0)),
                ('reward_amount', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('skretch_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('skretch_to', models.DateTimeField(blank=True, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('removed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reward.rewardwallet', to_field='wallet_username')),
            ],
        ),
        migrations.DeleteModel(
            name='RewardOrders',
        ),
    ]
