# Generated by Django 5.2.1 on 2025-06-02 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0004_rewardcards_delete_rewardorders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rewardcards',
            old_name='skretch_from',
            new_name='skrech_from',
        ),
        migrations.RenameField(
            model_name='rewardcards',
            old_name='skretch_to',
            new_name='skrech_to',
        ),
    ]
