# Generated by Django 5.2.1 on 2025-06-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0005_rename_skretch_from_rewardcards_skrech_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rewardcards',
            old_name='removed_date',
            new_name='scratch_from',
        ),
        migrations.RenameField(
            model_name='rewardcards',
            old_name='skrech_to',
            new_name='scratch_to',
        ),
        migrations.RemoveField(
            model_name='rewardcards',
            name='skrech_from',
        ),
        migrations.AddField(
            model_name='rewardcards',
            name='scratch_status',
            field=models.BooleanField(default=False),
        ),
    ]
