# Generated by Django 5.2.1 on 2025-06-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0006_rename_removed_date_rewardcards_scratch_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardcards',
            name='scratch_from',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
