# Generated by Django 5.2.1 on 2025-06-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0008_alter_rewardcards_reward_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardcards',
            name='reward_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
