# Generated by Django 5.2.1 on 2025-06-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0009_alter_rewardcards_reward_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardcards',
            name='final_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rewardcards',
            name='reward_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rewardcards',
            name='reward_rate',
            field=models.FloatField(default=0),
        ),
    ]
