# Generated by Django 5.2.1 on 2025-06-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0010_alter_rewardcards_final_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardcards',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rewardcards',
            name='reward_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rewardcards',
            name='reward_rate',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
